logging:
  level:
    org:
      springframework:
        cloud:
          sleuth: DEBUG
        web:
          servlet:
            DispatcherServlet: DEBUG
    root: debug
logback:
  logstash:
    encoder:
      customFields: '{"appName": ${spring.application.name}}'
    destination: 10.1.241.33:5188
    #    onMismatch: NEUTRAL
    onMismatch: DENY
demo:
  rocketmq:
    msgExtTopic: message-ext-topic
    orderTopic: order-paid-topic
    topic: string-topic
    transTopic: spring-transaction-topic
rocketmq:
  name-server: 192.168.111.162:9876
  producer:
    group: my-group1
    sendMessageTimeout: 6000
server:
  port: 12102
spring:
  application:
    name: rocketmq-starter
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      filter:
        slf4j:
          connection-log-enabled: false
          result-set-log-enabled: true
          statement-executable-sql-log-enable: true
          statement-log-enabled: false
      filters: stat,wall
      initial-size: 5
      max-active: 20
      max-pool-prepared-statement-per-connection-size: 20
      max-wait: 60000
      min-idle: 5
      password: lizhanyong
      pool-prepared-statements: true
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 300000
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://192.168.111.163:3306/ds0?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
      username: lizhanyong
      validation-query: select 1 from dual
      validation-query-timeout: 60000